import type { World } from '../world.ts';
import { hsl } from '../world.ts';

const alpha = (hex: string, a: number) => {
  const h = hex.replace('#', '');
  const n = parseInt(h.length === 3 ? h.split('').map(c => c + c).join('') : h, 16);
  return `rgba(${(n >> 16) & 255},${(n >> 8) & 255},${n & 255},${a})`;
};

export function emitCSS(w: World): string {
  const { ground, accent, payoff, ink, muted } = w.palette;
  const lightGround = hsl(ground).l > 0.5;
  const topo = w.id;

  return `/* =========================================================
   ${w.artist.toUpperCase()} — "${w.name.toUpperCase()}"
   ${w.logline}

   Generated by COLD OPEN. The palette was decided before the layout:
   ground ${ground}, one accent ${accent}, payoff ${payoff}.
   ========================================================= */

:root{
  --ground:${ground};
  --ink:${ink};
  --muted:${muted};
  --subtle:${alpha(ink, 0.32)};
  --accent:${accent};
  --accent-dim:${alpha(accent, 0.22)};
  --accent-line:${alpha(accent, 0.30)};
  --payoff:${payoff};
  --line:${alpha(ink, 0.14)};
  --f-disp:'${w.type.display.family}', system-ui, -apple-system, sans-serif;
  --f-mono:'${w.type.mono.family}', ui-monospace, 'SF Mono', monospace;
  --hud:.62rem;
  --gut:clamp(1.1rem, 4vw, 3rem);
}

*{ margin:0; padding:0; box-sizing:border-box; }
html{ background:var(--ground); scroll-behavior:smooth; }
body{
  background:var(--ground); color:var(--ink);
  font-family:var(--f-disp); overflow-x:hidden;
  -webkit-font-smoothing:antialiased; text-rendering:optimizeLegibility;
  min-height:100vh;
}
img,video{ display:block; max-width:100%; }
a{ color:inherit; }
.mono{ font-family:var(--f-mono); font-variant-numeric:tabular-nums; }
.sr-only{ position:absolute; width:1px; height:1px; overflow:hidden; clip:rect(0 0 0 0); white-space:nowrap; }
::selection{ background:var(--accent); color:${lightGround ? ground : ground}; }

/* ============ 1 · THE COLD OPEN — the threshold ritual ============ */
/* You cross something to get in. Not a splash screen: a gesture with a
   reward on the other side, and a failsafe so it can never trap anyone. */

#coldopen{
  position:fixed; inset:0; z-index:100;
  background:var(--ground);
  display:flex; align-items:center; justify-content:center;
  transition:opacity .9s cubic-bezier(.16,1,.3,1), visibility .9s;
}
#coldopen.crossed{ opacity:0; visibility:hidden; pointer-events:none; }

.co-ground{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; z-index:0; }
.co-tint{ position:absolute; inset:0; z-index:1; pointer-events:none;
  background:
    radial-gradient(120% 90% at 50% 45%, transparent 30%, ${alpha(ground, 0.72)} 78%, var(--ground) 100%),
    linear-gradient(180deg, ${alpha(ground, 0.55)} 0%, transparent 28%, transparent 62%, ${alpha(ground, 0.88)} 100%);
}
${w.ground.treatment.includes('scanlines') ? `.co-tint::after{ content:""; position:absolute; inset:0;
  background:repeating-linear-gradient(180deg, ${alpha(ink, 0.05)} 0 1px, transparent 1px 3px); opacity:.5; }` : ''}

.co-frame{ position:absolute; inset:clamp(.9rem,2.2vw,1.6rem); z-index:3; pointer-events:none; }
.co-frame span{ position:absolute; width:clamp(18px,3vw,34px); height:clamp(18px,3vw,34px); border:1px solid var(--accent-line); }
.co-frame span:nth-child(1){ top:0; left:0; border-right:0; border-bottom:0; }
.co-frame span:nth-child(2){ top:0; right:0; border-left:0; border-bottom:0; }
.co-frame span:nth-child(3){ bottom:0; left:0; border-right:0; border-top:0; }
.co-frame span:nth-child(4){ bottom:0; right:0; border-left:0; border-top:0; }

.co-body{ position:relative; z-index:5; text-align:center; padding:0 var(--gut); display:flex; flex-direction:column; align-items:center; gap:clamp(.7rem,2vh,1.3rem); }
.co-premise{ font-family:var(--f-mono); font-size:var(--hud); letter-spacing:.42em; text-transform:uppercase; color:var(--accent); font-weight:700; }
.co-word{
  font-family:var(--f-disp); font-weight:900; text-transform:uppercase;
  font-size:clamp(2.6rem, 13vw, 9.5rem); line-height:.84; letter-spacing:-.035em;
  color:var(--ink);
  ${lightGround ? '' : `text-shadow:0 0 clamp(30px,7vw,90px) ${alpha(accent, 0.30)};`}
}
.co-log{ font-family:var(--f-mono); font-size:clamp(.62rem,1.5vw,.78rem); letter-spacing:.2em; text-transform:uppercase; color:var(--muted); max-width:42ch; line-height:1.7; }

/* the gesture itself */
.co-gate{ margin-top:clamp(1rem,4vh,2.4rem); display:flex; flex-direction:column; align-items:center; gap:.75rem; }
.co-cta{
  font-family:var(--f-mono); font-size:clamp(.6rem,1.4vw,.72rem); letter-spacing:.3em; text-transform:uppercase;
  color:var(--ink); background:none; border:1px solid var(--accent-line); cursor:pointer;
  padding:.95rem 1.6rem; position:relative; overflow:hidden; isolation:isolate;
  transition:color .3s, border-color .3s;
}
.co-cta:hover,.co-cta:focus-visible{ border-color:var(--accent); outline:none; }
/* hold-to-enter fills; scroll/press just pulse */
.co-cta .fill{ position:absolute; inset:0; z-index:-1; background:var(--accent); transform:scaleX(var(--held,0)); transform-origin:left; transition:transform .12s linear; }
.co-cta[data-held="1"]{ color:var(--ground); }
.co-hint{ font-family:var(--f-mono); font-size:.58rem; letter-spacing:.26em; text-transform:uppercase; color:var(--subtle); }
.co-arrow{ font-size:1.1rem; color:var(--accent); animation:bob 2.1s ease-in-out infinite; }
@keyframes bob{ 0%,100%{ transform:translateY(0); opacity:.55 } 50%{ transform:translateY(7px); opacity:1 } }

.co-serial{ position:absolute; left:var(--gut); bottom:clamp(1.1rem,3vh,2rem); z-index:5;
  font-family:var(--f-mono); font-size:.56rem; letter-spacing:.2em; text-transform:uppercase; color:var(--subtle); }
.co-status{ position:absolute; right:var(--gut); bottom:clamp(1.1rem,3vh,2rem); z-index:5;
  font-family:var(--f-mono); font-size:.56rem; letter-spacing:.2em; text-transform:uppercase; color:var(--accent); display:flex; align-items:center; gap:.5rem; }
.live-dot{ width:6px; height:6px; border-radius:50%; background:var(--accent); animation:pulse 1.7s ease-in-out infinite; }
@keyframes pulse{ 0%,100%{ opacity:1; box-shadow:0 0 0 0 var(--accent-dim) } 50%{ opacity:.35; box-shadow:0 0 0 7px transparent } }

/* ============ 2 · HUD — technical chrome, always on ============ */
.hud{ position:fixed; z-index:60; font-family:var(--f-mono); font-size:var(--hud);
  letter-spacing:.24em; text-transform:uppercase; pointer-events:none; color:var(--muted); mix-blend-mode:${lightGround ? 'normal' : 'plus-lighter'}; }
.hud-tl{ top:1.1rem; left:var(--gut); color:var(--accent); font-weight:700; }
.hud-tl i{ color:var(--subtle); font-style:normal; font-weight:400; }
.hud-tr{ top:1.1rem; right:var(--gut); }
.hud-bl{ bottom:1.1rem; left:var(--gut); }

/* ============ 3 · SOUND — a first-class control, not a mute toggle ======= */
.sound{
  position:fixed; z-index:70; right:var(--gut); bottom:1.05rem;
  display:flex; align-items:center; gap:.6rem; cursor:pointer;
  font-family:var(--f-mono); font-size:var(--hud); letter-spacing:.24em; text-transform:uppercase;
  background:${alpha(ground, 0.72)}; backdrop-filter:blur(9px);
  border:1px solid var(--accent-line); color:var(--ink);
  padding:.62rem .95rem; transition:border-color .25s, color .25s;
}
.sound:hover{ border-color:var(--accent); }
.sound .bars{ display:flex; align-items:flex-end; gap:2px; height:12px; }
.sound .bars i{ width:2px; background:var(--accent); height:30%; transform-origin:bottom; }
.sound.on .bars i{ animation:eq .9s ease-in-out infinite; }
.sound.on .bars i:nth-child(2){ animation-delay:.15s } .sound.on .bars i:nth-child(3){ animation-delay:.3s } .sound.on .bars i:nth-child(4){ animation-delay:.45s }
@keyframes eq{ 0%,100%{ height:28% } 50%{ height:100% } }

/* ============ 4 · SHELL ============ */
main{ position:relative; z-index:10; }
.ground-bed{ position:fixed; inset:0; z-index:0; overflow:hidden; }
.ground-bed video,.ground-bed img{ width:100%; height:100%; object-fit:cover; ${w.ground.treatment.includes('desaturate') ? 'filter:grayscale(1) contrast(1.12);' : ''} }
.ground-bed::after{ content:""; position:absolute; inset:0; background:linear-gradient(180deg, ${alpha(ground, 0.86)}, ${alpha(ground, 0.96)} 40%, var(--ground) 82%); }
${w.ground.treatment.includes('grain') ? `.grain{ position:fixed; inset:-150%; z-index:1; pointer-events:none; opacity:.045; mix-blend-mode:overlay;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='220'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.82' numOctaves='3'/%3E%3C/filter%3E%3Crect width='220' height='220' filter='url(%23n)'/%3E%3C/svg%3E");
  animation:grainshift 5s steps(6) infinite; }
@keyframes grainshift{ 0%{transform:translate(0,0)} 20%{transform:translate(-4%,3%)} 40%{transform:translate(3%,-4%)} 60%{transform:translate(-3%,-3%)} 80%{transform:translate(4%,2%)} 100%{transform:translate(0,0)} }` : ''}

section{ padding:clamp(4.5rem,13vh,10rem) var(--gut); position:relative; }
.slug{ font-family:var(--f-mono); font-size:var(--hud); letter-spacing:.34em; text-transform:uppercase; color:var(--accent); font-weight:700; margin-bottom:1.1rem; display:flex; align-items:center; gap:.8rem; }
.slug::after{ content:""; flex:1; height:1px; background:var(--accent-line); }
h2{ font-family:var(--f-disp); font-weight:900; text-transform:uppercase; letter-spacing:-.02em; line-height:.92;
  font-size:clamp(1.8rem,6vw,4.2rem); margin-bottom:1.6rem; }
p{ line-height:1.75; color:var(--muted); max-width:62ch; font-size:clamp(.95rem,1.6vw,1.06rem); }

.reveal{ opacity:0; transform:translateY(26px); transition:opacity .8s cubic-bezier(.16,1,.3,1), transform .8s cubic-bezier(.16,1,.3,1); }
.reveal.in{ opacity:1; transform:none; }

/* ============ 5 · LIVE NUMBERS — the flex ============ */
.figures{ display:grid; grid-template-columns:repeat(auto-fit,minmax(170px,1fr)); gap:1px; background:var(--line); border:1px solid var(--line); margin:2.5rem 0; }
.fig{ background:var(--ground); padding:clamp(1.3rem,3vw,2rem); position:relative; }
.fig b{ display:block; font-family:var(--f-disp); font-weight:900; font-size:clamp(1.6rem,4.6vw,3rem); line-height:1; letter-spacing:-.03em; color:var(--ink); font-variant-numeric:tabular-nums; }
.fig .fl{ display:block; font-family:var(--f-mono); font-size:.58rem; letter-spacing:.24em; text-transform:uppercase; color:var(--muted); margin-top:.6rem; }
.fig .src{ position:absolute; top:.7rem; right:.7rem; font-family:var(--f-mono); font-size:.5rem; letter-spacing:.14em; color:var(--subtle); text-decoration:none; border-bottom:1px dotted var(--subtle); }
.fig .src:hover{ color:var(--accent); border-color:var(--accent); }
.fig.sealed b{ color:var(--subtle); letter-spacing:.06em; font-size:clamp(1.3rem,3.4vw,2.2rem); }
.fig.sealed .fl{ color:var(--accent); }

/* ============ 6 · THE CATALOGUE ============ */
.rack{ display:grid; gap:clamp(.7rem,1.6vw,1.15rem); grid-template-columns:repeat(auto-fill,minmax(min(100%,255px),1fr)); }
.unit{ position:relative; aspect-ratio:16/9; overflow:hidden; border:1px solid var(--line); background:${alpha(ink, 0.04)}; text-decoration:none; display:block; isolation:isolate;
  transition:border-color .3s, transform .5s cubic-bezier(.16,1,.3,1); }
.unit:hover,.unit:focus-visible{ border-color:var(--accent); transform:translateY(-4px); outline:none; }
.unit img{ position:absolute; inset:0; width:100%; height:100%; object-fit:cover; z-index:-1; transition:transform .7s cubic-bezier(.16,1,.3,1), filter .4s; ${w.ground.treatment.includes('desaturate') ? 'filter:grayscale(.85);' : ''} }
.unit:hover img{ transform:scale(1.06); filter:none; }
.unit::after{ content:""; position:absolute; inset:0; z-index:0; background:linear-gradient(180deg, transparent 34%, ${alpha(ground, 0.9)} 100%); }
.u-meta{ position:absolute; left:0; right:0; bottom:0; z-index:2; padding:.9rem .85rem .8rem; }
.u-n{ font-family:var(--f-mono); font-size:.54rem; letter-spacing:.24em; color:var(--accent); display:block; margin-bottom:.35rem; }
.u-t{ font-family:var(--f-disp); font-weight:900; text-transform:uppercase; font-size:clamp(.86rem,1.9vw,1.05rem); letter-spacing:-.012em; line-height:1.05; }
.u-s{ font-family:var(--f-mono); font-size:.55rem; letter-spacing:.16em; text-transform:uppercase; color:var(--muted); margin-top:.3rem; display:block; }
.u-corner{ position:absolute; top:.6rem; left:.6rem; z-index:2; width:13px; height:13px; border-left:1px solid var(--accent-line); border-top:1px solid var(--accent-line); }

/* the climax object — the ONE thing the site is built around */
.climax{ position:relative; border:1px solid var(--accent-line); padding:clamp(1.6rem,5vw,3.6rem); margin:clamp(2rem,6vh,4rem) 0;
  background:linear-gradient(160deg, ${alpha(accent, 0.09)}, transparent 62%); overflow:hidden; }
.climax::before{ content:""; position:absolute; inset:0; background:radial-gradient(90% 130% at 88% -10%, ${alpha(payoff, 0.16)}, transparent 60%); pointer-events:none; }
.climax .stamp{ display:inline-block; font-family:var(--f-mono); font-size:.58rem; letter-spacing:.3em; text-transform:uppercase;
  color:var(--payoff); border:1px solid ${alpha(payoff, 0.5)}; padding:.42rem .8rem; margin-bottom:1.1rem; }
.climax h3{ font-family:var(--f-disp); font-weight:900; text-transform:uppercase; letter-spacing:-.028em; line-height:.9;
  font-size:clamp(2rem,8vw,5.4rem); color:var(--payoff); margin-bottom:.7rem; }
.climax .cx-sub{ font-family:var(--f-mono); font-size:clamp(.6rem,1.4vw,.74rem); letter-spacing:.22em; text-transform:uppercase; color:var(--muted); }

/* ============ 7 · THE RAIL — booking that actually delivers ============ */
.rail{ border:1px solid var(--accent-line); padding:clamp(1.5rem,4.5vw,3rem); background:${alpha(accent, 0.05)}; }
.rail form{ display:grid; gap:.9rem; margin-top:1.6rem; max-width:38rem; }
.rail label{ font-family:var(--f-mono); font-size:.56rem; letter-spacing:.26em; text-transform:uppercase; color:var(--muted); display:block; margin-bottom:.4rem; }
.rail input,.rail textarea,.rail select{ width:100%; background:${alpha(ink, 0.05)}; border:1px solid var(--line); color:var(--ink);
  padding:.85rem .9rem; font-family:var(--f-mono); font-size:.82rem; transition:border-color .25s; }
.rail input:focus,.rail textarea:focus,.rail select:focus{ outline:none; border-color:var(--accent); }
.rail textarea{ min-height:7rem; resize:vertical; }
.rail button{ font-family:var(--f-mono); font-size:.66rem; letter-spacing:.3em; text-transform:uppercase; font-weight:700;
  background:var(--accent); color:var(--ground); border:0; padding:1.05rem 1.5rem; cursor:pointer; transition:filter .25s; }
.rail button:hover{ filter:brightness(1.15); }
.rail button[disabled]{ opacity:.5; cursor:wait; }
.rail .alt{ margin-top:1.1rem; font-family:var(--f-mono); font-size:.6rem; letter-spacing:.16em; color:var(--muted); }
.rail .alt a{ color:var(--accent); }
.form-msg{ font-family:var(--f-mono); font-size:.66rem; letter-spacing:.14em; margin-top:.9rem; min-height:1.2em; }
.form-msg.ok{ color:var(--accent); } .form-msg.err{ color:#ff6b6b; }

/* links out */
.links{ display:flex; flex-wrap:wrap; gap:.55rem; margin-top:2rem; }
.links a{ font-family:var(--f-mono); font-size:.6rem; letter-spacing:.24em; text-transform:uppercase; text-decoration:none;
  border:1px solid var(--line); padding:.72rem 1rem; color:var(--muted); transition:color .25s, border-color .25s; }
.links a:hover{ color:var(--accent); border-color:var(--accent); }

/* ============ 8 · SOURCES — the site shows its work ============ */
.sources{ border-top:1px solid var(--line); }
.sources table{ width:100%; border-collapse:collapse; font-family:var(--f-mono); font-size:.66rem; margin-top:1.4rem; }
.sources th{ text-align:left; letter-spacing:.24em; text-transform:uppercase; color:var(--accent); font-size:.56rem; padding:.7rem .8rem; border-bottom:1px solid var(--accent-line); font-weight:700; }
.sources td{ padding:.7rem .8rem; border-bottom:1px solid var(--line); color:var(--muted); vertical-align:top; }
.sources td a{ color:var(--accent); text-decoration:none; border-bottom:1px dotted var(--accent-line); word-break:break-all; }
.sources .wrap{ overflow-x:auto; }

footer{ padding:2.5rem var(--gut) 6.5rem; border-top:1px solid var(--line);
  font-family:var(--f-mono); font-size:.58rem; letter-spacing:.2em; text-transform:uppercase; color:var(--subtle);
  display:flex; justify-content:space-between; gap:1rem; flex-wrap:wrap; }
footer a{ color:var(--muted); text-decoration:none; } footer a:hover{ color:var(--accent); }

@media (max-width:640px){
  .hud-tr{ display:none; }
  .sound{ right:auto; left:var(--gut); }
  .hud-bl{ display:none; }
}

@media (prefers-reduced-motion:reduce){
  *{ animation-duration:.001ms !important; animation-iteration-count:1 !important; transition-duration:.001ms !important; scroll-behavior:auto !important; }
  .reveal{ opacity:1; transform:none; }
  #coldopen{ transition:none; }
}
`;
}
