import type { World } from '../world.ts';

export function emitJS(w: World): string {
  return `/* ${w.artist} — "${w.name}". Generated by COLD OPEN.
   Vanilla, no framework, no build step. Everything degrades: if this file
   fails to load, the cold open removes itself on a CSS timer and the page
   below is fully readable. */
(function () {
  'use strict';
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;

  /* ---------- 1 · THE THRESHOLD RITUAL ----------
     You cross something to get in. Three rules make this a ritual instead of
     a toll booth: the gesture is the one the world implies, it can always be
     skipped by keyboard, and it self-opens after maxDwell so nobody is ever
     trapped behind it. */
  var co = document.getElementById('coldopen');
  var crossed = false;

  function cross() {
    if (crossed || !co) return;
    crossed = true;
    co.classList.add('crossed');
    document.body.style.overflow = '';
    var bed = document.querySelector('[data-bed]');
    if (bed && !reduce) { bed.play().catch(function () {}); }
    ${w.sound && !w.sound.startsMuted ? `var a = document.getElementById('bed');
    if (a) { a.volume = 0; a.play().then(function(){ fade(a, 0.55, 1400); setSound(true); }).catch(function(){}); }` : ''}
    setTimeout(function () { if (co && co.parentNode) co.setAttribute('aria-hidden', 'true'); }, 950);
    try { history.replaceState(null, '', '#' + '${w.lexicon.proof.toLowerCase().replace(/[^a-z0-9]+/g, '-')}'); } catch (e) {}
  }

  if (co) {
    document.body.style.overflow = 'hidden';
    var gesture = co.getAttribute('data-gesture') || 'press';
    var dwell = parseInt(co.getAttribute('data-dwell') || '0', 10);
    var btn = document.getElementById('crossBtn');

    if (gesture === 'hold') {
      /* hold: the button fills. Releasing early resets — you have to mean it. */
      var held = 0, raf = null, HOLD = 900;
      var fill = btn && btn.querySelector('.fill');
      function tick(t0) {
        return function step(now) {
          held = Math.min(1, (now - t0) / HOLD);
          if (fill) fill.style.setProperty('--held', held);
          if (btn) btn.setAttribute('data-held', held > 0.55 ? '1' : '0');
          if (held >= 1) { cross(); return; }
          raf = requestAnimationFrame(step);
        };
      }
      function start(e) { e.preventDefault(); if (raf) cancelAnimationFrame(raf); raf = requestAnimationFrame(tick(performance.now())); }
      function stop() { if (raf) cancelAnimationFrame(raf); raf = null; held = 0; if (fill) fill.style.setProperty('--held', 0); if (btn) btn.setAttribute('data-held', '0'); }
      if (btn) {
        btn.addEventListener('pointerdown', start);
        ['pointerup', 'pointerleave', 'pointercancel'].forEach(function (ev) { btn.addEventListener(ev, stop); });
        btn.addEventListener('keydown', function (e) { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); cross(); } });
      }
    } else if (gesture === 'scroll') {
      var acc = 0;
      window.addEventListener('wheel', function (e) { if (crossed) return; acc += e.deltaY; if (acc > 90) cross(); }, { passive: true });
      var y0 = null;
      window.addEventListener('touchstart', function (e) { y0 = e.touches[0].clientY; }, { passive: true });
      window.addEventListener('touchmove', function (e) { if (y0 !== null && y0 - e.touches[0].clientY > 42) cross(); }, { passive: true });
      if (btn) btn.addEventListener('click', cross);
    } else {
      if (btn) btn.addEventListener('click', cross);
    }

    /* always escapable, always self-opening — a ritual, never a wall */
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape' || e.key === 'Enter') cross(); });
    if (reduce) { cross(); }
    else if (dwell > 0) { setTimeout(cross, dwell); }
  }

  /* ---------- 2 · SOUND AS A FIRST-CLASS CONTROL ----------
     Not a mute icon in a corner. A labelled control that says what it will
     play, remembers the choice, and never autoplays audibly without a gesture. */
  function fade(el, to, ms) {
    var from = el.volume, t0 = performance.now();
    (function step(now) {
      var k = Math.min(1, (now - t0) / ms);
      el.volume = from + (to - from) * k;
      if (k < 1) requestAnimationFrame(step);
    })(t0);
  }
  var sBtn = document.getElementById('soundBtn');
  var audio = document.getElementById('bed');
  var sOn = false;
  function setSound(on) {
    sOn = on;
    if (!sBtn) return;
    sBtn.classList.toggle('on', on);
    sBtn.setAttribute('aria-pressed', String(on));
    var lbl = sBtn.querySelector('.s-label');
    if (lbl) lbl.textContent = on ? '${(w.sound?.label ?? 'SOUND').toUpperCase()} ON' : '${(w.sound?.label ?? 'SOUND').toUpperCase()} OFF';
    try { localStorage.setItem('co-sound', on ? '1' : '0'); } catch (e) {}
  }
  if (sBtn && audio) {
    setSound(false);
    sBtn.addEventListener('click', function () {
      if (sOn) { fade(audio, 0, 400); setTimeout(function () { audio.pause(); }, 420); setSound(false); }
      else { audio.volume = 0; audio.play().then(function () { fade(audio, 0.55, 900); setSound(true); }).catch(function () {}); }
    });
    document.addEventListener('visibilitychange', function () { if (document.hidden && sOn) audio.pause(); else if (!document.hidden && sOn) audio.play().catch(function () {}); });
  }

  /* ---------- 2b · THE DIAL ----------
     Swaps the page's register. Only prose and section names move; every
     NUMBER stays exactly as it was, because a figure does not change
     language and re-rendering one is how a translated site starts lying. */
  var regEl = document.getElementById('registers');
  if (regEl) {
    var REG = JSON.parse(regEl.textContent || '{}');
    var base = {};
    document.querySelectorAll('[data-t]').forEach(function (el) { base[el.getAttribute('data-t')] = el.innerHTML; });
    var baseCode = document.querySelector('.dial-b.is-on') && document.querySelector('.dial-b.is-on').getAttribute('data-reg');

    function setRegister(code) {
      var r = REG[code];
      document.querySelectorAll('.dial-b').forEach(function (b) {
        var on = b.getAttribute('data-reg') === code;
        b.classList.toggle('is-on', on);
        b.setAttribute('aria-pressed', String(on));
      });
      document.documentElement.lang = code;
      document.querySelectorAll('[data-t]').forEach(function (el) {
        var k = el.getAttribute('data-t');
        if (code === baseCode || !r) { el.innerHTML = base[k]; return; }
        if (k === 'logline' && r.logline) el.textContent = r.logline;
        else if (k === 'story' && r.story) el.innerHTML = r.story.map(function (p) { return '<p>' + p.replace(/[&<>]/g, '') + '</p>'; }).join('');
        else if (k.indexOf('lex.') === 0 && r.lexicon && r.lexicon[k.slice(4)]) el.textContent = r.lexicon[k.slice(4)];
        else el.innerHTML = base[k];
      });
      try { localStorage.setItem('co-register', code); } catch (e) {}
    }
    document.querySelectorAll('.dial-b').forEach(function (b) {
      b.addEventListener('click', function () { setRegister(b.getAttribute('data-reg')); });
    });
    try {
      var saved = localStorage.getItem('co-register');
      if (saved && REG[saved]) setRegister(saved);
      else {
        // meet the visitor in their own language if we speak it
        var nav = (navigator.language || '').slice(0, 2);
        if (REG[nav]) setRegister(nav);
      }
    } catch (e) {}
  }

  /* ---------- 3 · REVEALS + LIVE-NUMBER COUNT-UP ----------
     The count-up animates TO the value already in the DOM. If JS dies the
     real number is still printed — the animation is decoration over truth,
     never the source of it. */
  var io = 'IntersectionObserver' in window ? new IntersectionObserver(function (es) {
    es.forEach(function (e) {
      if (!e.isIntersecting) return;
      e.target.classList.add('in');
      e.target.querySelectorAll('[data-count]').forEach(countUp);
      io.unobserve(e.target);
    });
  }, { threshold: 0.12, rootMargin: '0px 0px -8% 0px' }) : null;

  document.querySelectorAll('.reveal').forEach(function (el) {
    if (io && !reduce) io.observe(el); else el.classList.add('in');
  });

  function countUp(el) {
    var target = parseFloat(el.getAttribute('data-count'));
    if (!target || reduce || el.dataset.done) return;
    el.dataset.done = '1';
    var dur = 1500, t0 = performance.now();
    (function step(now) {
      var k = Math.min(1, (now - t0) / dur);
      var eased = 1 - Math.pow(1 - k, 3);
      el.textContent = Math.round(target * eased).toLocaleString('en-US');
      if (k < 1) requestAnimationFrame(step);
      else el.textContent = target.toLocaleString('en-US');
    })(t0);
  }

  /* ---------- 4 · HUD READOUT ---------- */
  var readout = document.getElementById('hudReadout');
  if (readout && !reduce) {
    var base = readout.textContent;
    window.addEventListener('scroll', function () {
      var p = Math.min(100, Math.round(scrollY / Math.max(1, document.body.scrollHeight - innerHeight) * 100));
      readout.textContent = base + ' · ' + String(p).padStart(3, '0') + '%';
    }, { passive: true });
  }

  /* ---------- 5 · THE RAIL ----------
     Submits over fetch so the visitor never leaves the world, and reports the
     REAL result. A form that says "thanks!" regardless of what the server did
     is worse than no form, because it hides a dead rail. */
  var form = document.getElementById('railForm');
  var msg = document.getElementById('formMsg');
  if (form) {
    form.addEventListener('submit', function (e) {
      e.preventDefault();
      if (form.querySelector('[name="_gotcha"]').value) return;
      var btn = form.querySelector('button[type="submit"]');
      var original = btn.textContent;
      btn.disabled = true; btn.textContent = 'SENDING…';
      msg.className = 'form-msg mono'; msg.textContent = '';
      fetch(form.action, { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } })
        .then(function (r) {
          if (!r.ok) throw new Error('HTTP ' + r.status);
          form.reset();
          msg.className = 'form-msg mono ok';
          msg.textContent = 'RECEIVED. YOU WILL HEAR BACK.';
        })
        .catch(function (err) {
          msg.className = 'form-msg mono err';
          msg.textContent = 'DID NOT SEND (' + err.message + '). EMAIL INSTEAD.';
        })
        .finally(function () { btn.disabled = false; btn.textContent = original; });
    });
  }
})();
`;
}
