import type { World } from '../world.ts';

export function emitSpatialJS(w: World): string {
  return `/* ${w.artist} — "${w.name}". SPATIAL. Generated by COLD OPEN.
   The threshold here is not a button that dismisses an overlay — it opens the
   object, and the object stays open. Nothing is hidden behind it: if this file
   never loads, the case renders open and every track is a working link. */
(function () {
  'use strict';
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  var el = document.getElementById('case');
  var btn = document.getElementById('openBtn');
  var gate = document.getElementById('gate');
  var opened = false;

  function open() {
    if (opened || !el) return;
    opened = true;
    el.classList.add('open');
    if (gate) gate.classList.add('gone');
    ${w.sound ? `var a = document.getElementById('bed');
    if (a && localStorage.getItem('co-sound') === '1') { a.volume = 0; a.play().then(function(){ fade(a, .5, 1200); setSound(true); }).catch(function(){}); }` : ''}
    /* Bring the whole object into view, lid included. Scrolling to the base
       put the mirror above the fold, which throws away the one moment the
       threshold exists to deliver. */
    setTimeout(function () {
      el.scrollIntoView({ behavior: reduce ? 'auto' : 'smooth', block: 'center' });
    }, 950);
  }

  if (btn && el) {
    /* Hold to lift the lid. A latch you have to keep pressure on is the
       gesture the object implies; a single click would be a door, not a lid. */
    var HOLD = 750, raf = null, fill = btn.querySelector('.fill');
    function step(t0) {
      return function frame(now) {
        var k = Math.min(1, (now - t0) / HOLD);
        if (fill) fill.style.setProperty('--held', k);
        btn.setAttribute('data-held', k > .5 ? '1' : '0');
        if (k >= 1) { open(); return; }
        raf = requestAnimationFrame(frame);
      };
    }
    function down(e) { e.preventDefault(); if (raf) cancelAnimationFrame(raf); raf = requestAnimationFrame(step(performance.now())); }
    function up() { if (raf) cancelAnimationFrame(raf); raf = null; if (fill) fill.style.setProperty('--held', 0); btn.setAttribute('data-held', '0'); }
    btn.addEventListener('pointerdown', down);
    ['pointerup', 'pointerleave', 'pointercancel'].forEach(function (ev) { btn.addEventListener(ev, up); });
    /* keyboard and reduced-motion never have to hold anything */
    btn.addEventListener('keydown', function (e) { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); } });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape' || e.key === 'Enter') open(); });
    /* a scroll past the object opens it too — nobody gets stuck at a closed box */
    window.addEventListener('wheel', function (e) { if (e.deltaY > 30) open(); }, { passive: true });
    window.addEventListener('touchmove', function () { open(); }, { passive: true, once: true });
    if (reduce) open();
    setTimeout(open, 14000);
  } else if (el) { el.classList.add('open'); }

  /* ---------- sound ---------- */
  function fade(a, to, ms) { var f = a.volume, t0 = performance.now();
    (function s(n){ var k = Math.min(1,(n-t0)/ms); a.volume = f+(to-f)*k; if(k<1) requestAnimationFrame(s); })(t0); }
  var sBtn = document.getElementById('soundBtn'), audio = document.getElementById('bed'), sOn = false;
  function setSound(on) {
    sOn = on; if (!sBtn) return;
    sBtn.classList.toggle('on', on); sBtn.setAttribute('aria-pressed', String(on));
    var l = sBtn.querySelector('.s-label');
    if (l) l.textContent = on ? '${(w.sound?.label ?? 'SOUND').toUpperCase()} ON' : '${(w.sound?.label ?? 'SOUND').toUpperCase()} OFF';
    try { localStorage.setItem('co-sound', on ? '1' : '0'); } catch (e) {}
  }
  if (sBtn && audio) {
    setSound(false);
    sBtn.addEventListener('click', function () {
      if (sOn) { fade(audio, 0, 350); setTimeout(function(){ audio.pause(); }, 380); setSound(false); }
      else { audio.volume = 0; audio.play().then(function(){ fade(audio, .5, 900); setSound(true); }).catch(function(){}); }
    });
  }

  /* ---------- the language dial ----------
     English leads. Prose and section names move; every NUMBER stays exactly as
     it was, because a figure does not change language and re-rendering one is
     how a translated site starts lying. */
  var regEl = document.getElementById('registers');
  if (regEl) {
    var REG = JSON.parse(regEl.textContent || '{}');
    var base = {};
    document.querySelectorAll('[data-t]').forEach(function (n) { base[n.getAttribute('data-t')] = n.innerHTML; });
    var baseCode = (document.querySelector('.dial-b.is-on') || {}).getAttribute
      ? document.querySelector('.dial-b.is-on').getAttribute('data-reg') : 'en';

    function setRegister(code) {
      var r = REG[code];
      document.querySelectorAll('.dial-b').forEach(function (b) {
        var on = b.getAttribute('data-reg') === code;
        b.classList.toggle('is-on', on); b.setAttribute('aria-pressed', String(on));
      });
      document.documentElement.lang = code;
      document.querySelectorAll('[data-t]').forEach(function (n) {
        var k = n.getAttribute('data-t');
        if (code === baseCode || !r) { n.innerHTML = base[k]; return; }
        if (k === 'logline' && r.logline) n.textContent = r.logline;
        else if (k === 'mirror' && r.mirror) n.textContent = r.mirror;
        else if (k === 'story' && r.story && r.story.length) n.innerHTML = r.story.map(function (p) { return '<p>' + p.replace(/[&<>]/g, '') + '</p>'; }).join('');
        else if (k.indexOf('lex.') === 0 && r.lexicon && r.lexicon[k.slice(4)]) n.textContent = r.lexicon[k.slice(4)];
        else n.innerHTML = base[k];
      });
      try { localStorage.setItem('co-register', code); } catch (e) {}
    }
    document.querySelectorAll('.dial-b').forEach(function (b) {
      b.addEventListener('click', function () { setRegister(b.getAttribute('data-reg')); });
    });
    /* A remembered choice is honoured. A browser language is NOT auto-applied:
       English leads by decision, and silently switching the page out from under
       a visitor because of a locale is a worse first impression than a click. */
    try { var saved = localStorage.getItem('co-register'); if (saved && REG[saved]) setRegister(saved); } catch (e) {}
  }

  /* ---------- reveals + count-up ---------- */
  var io = 'IntersectionObserver' in window ? new IntersectionObserver(function (es) {
    es.forEach(function (e) {
      if (!e.isIntersecting) return;
      e.target.classList.add('in');
      e.target.querySelectorAll('[data-count]').forEach(countUp);
      io.unobserve(e.target);
    });
  }, { threshold: .12, rootMargin: '0px 0px -8% 0px' }) : null;
  document.querySelectorAll('.reveal').forEach(function (n) { if (io && !reduce) io.observe(n); else n.classList.add('in'); });

  function countUp(n) {
    var target = parseFloat(n.getAttribute('data-count'));
    if (!target || reduce || n.dataset.done) return;
    n.dataset.done = '1';
    var dur = 1400, t0 = performance.now();
    (function s(now) {
      var k = Math.min(1, (now - t0) / dur), e = 1 - Math.pow(1 - k, 3);
      n.textContent = Math.round(target * e).toLocaleString('en-US');
      if (k < 1) requestAnimationFrame(s); else n.textContent = target.toLocaleString('en-US');
    })(t0);
  }

  /* ---------- readout ---------- */
  var ro = document.getElementById('hudReadout');
  if (ro && !reduce) {
    var b0 = ro.textContent;
    window.addEventListener('scroll', function () {
      var p = Math.min(100, Math.round(scrollY / Math.max(1, document.body.scrollHeight - innerHeight) * 100));
      ro.textContent = b0 + ' · ' + String(p).padStart(3, '0') + '%';
    }, { passive: true });
  }

  /* ---------- the rail ---------- */
  var form = document.getElementById('railForm'), msg = document.getElementById('formMsg');
  if (form) form.addEventListener('submit', function (e) {
    e.preventDefault();
    if (form.querySelector('[name="_gotcha"]').value) return;
    var b = form.querySelector('button[type="submit"]'), o = b.textContent;
    b.disabled = true; b.textContent = 'SENDING…'; msg.className = 'form-msg mono'; msg.textContent = '';
    fetch(form.action, { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } })
      .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status);
        form.reset(); msg.className = 'form-msg mono ok'; msg.textContent = 'RECEIVED. YOU WILL HEAR BACK.'; })
      .catch(function (err) { msg.className = 'form-msg mono err'; msg.textContent = 'DID NOT SEND (' + err.message + '). EMAIL INSTEAD.'; })
      .finally(function () { b.disabled = false; b.textContent = o; });
  });
})();
`;
}
