import type { World } from '../world.ts';

export function emitSpatialJS(w: World): string {
  const soundLabel = (w.sound?.label ?? 'SOUND').toUpperCase();
  return `/* ${w.artist} — "${w.name}". SPATIAL. Generated by COLD OPEN.
   The threshold is the language choice: three tags on the handle, and picking
   one both sets the register and opens the case. One gesture, not two, and it
   sits at eye level rather than in a corner nobody looks at.

   Nothing is hidden behind it. If this file never loads, the case renders open
   and every track is a working link. */
(function () {
  'use strict';
  var reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;
  var el = document.getElementById('case');
  var tags = document.getElementById('tags');
  var tagline = document.getElementById('tagline');
  var dial = document.getElementById('dial');
  var audio = document.getElementById('bed');
  var opened = false;

  /* ---------- registers ----------
     Prose and section names move. Every NUMBER stays exactly as it was: a
     figure does not change language, and re-rendering one is how a translated
     site starts lying. */
  var REG = {}, base = {}, baseCode = 'en';
  (function () {   // keep the original MRZ so the issuing state can be re-templated
    var m = document.getElementById('pp-mrz');
    if (m) m.dataset.pt = m.innerHTML;
  })();
  var regEl = document.getElementById('registers');
  if (regEl) {
    try { REG = JSON.parse(regEl.textContent || '{}'); } catch (e) {}
    document.querySelectorAll('[data-t]').forEach(function (n) { base[n.getAttribute('data-t')] = n.innerHTML; });
    var first = document.querySelector('.dial-b');
    if (first) baseCode = first.getAttribute('data-reg');
  }

  function setRegister(code) {
    var r = REG[code];
    document.querySelectorAll('.dial-b').forEach(function (b) {
      var on = b.getAttribute('data-reg') === code;
      b.classList.toggle('is-on', on); b.setAttribute('aria-pressed', String(on));
    });
    document.documentElement.lang = code;
    document.querySelectorAll('[data-t]').forEach(function (n) {
      var k = n.getAttribute('data-t');
      if (code === baseCode || !r) { n.innerHTML = base[k]; return; }
      if (k === 'logline' && r.logline) n.textContent = r.logline;
      else if (k === 'mirror' && r.mirror) n.textContent = r.mirror;
      else if (k === 'prompt' && r.prompt) n.innerHTML = r.prompt;
      else if (k === 'story' && r.story && r.story.length) {
        n.innerHTML = r.story.map(function (p) { return '<p>' + p.replace(/[&<>]/g, '') + '</p>'; }).join('');
      }
      else if (k.indexOf('lex.') === 0 && r.lexicon && r.lexicon[k.slice(4)]) n.textContent = r.lexicon[k.slice(4)];
      else n.innerHTML = base[k];
    });
    /* the passport follows the language: born under one, raised under another */
    var pp = document.getElementById('pp');
    if (pp) pp.setAttribute('data-book', code);
    var mrz = document.getElementById('pp-mrz');
    if (mrz && mrz.dataset.pt) {
      var iso = code === 'en' ? 'CAN' : code === 'es' ? 'DOM' : 'PRT';
      mrz.innerHTML = mrz.dataset.pt.replace(/PRT/g, iso);
    }
    try { localStorage.setItem('co-register', code); } catch (e) {}
  }

  /* ---------- the case ---------- */
  function open(code) {
    if (code) setRegister(code);
    if (opened || !el) return;
    opened = true;
    el.classList.add('open');
    if (tags) tags.classList.add('gone');
    if (tagline) { tagline.style.transition = 'opacity .4s'; tagline.style.opacity = '0'; }
    if (dial) dial.classList.add('shown');
    var g = document.querySelector('#ground video');
    if (g && !reduce) g.play().catch(function () {});
    try { if (audio && localStorage.getItem('co-sound') === '1') {
      audio.volume = 0; audio.play().then(function () { fade(audio, .5, 1200); setSound(true); }).catch(function () {});
    } } catch (e) {}
  }

  if (tags) {
    tags.querySelectorAll('.tag').forEach(function (t) {
      t.addEventListener('click', function () { open(t.getAttribute('data-reg')); });
    });
  }
  if (dial) {
    dial.querySelectorAll('.dial-b').forEach(function (b) {
      b.addEventListener('click', function () { setRegister(b.getAttribute('data-reg')); });
    });
  }

  /* Nobody gets stuck at a shut case: a scroll, a key, or simply waiting all
     open it in the default register. The tag is the invitation, not a gate. */
  if (el) {
    window.addEventListener('wheel', function (e) { if (e.deltaY > 24) open(); }, { passive: true });
    window.addEventListener('touchmove', function () { open(); }, { passive: true });
    document.addEventListener('keydown', function (e) { if (e.key === 'Enter' || e.key === 'Escape' || e.key === ' ') open(); });
    if (reduce) open(); else setTimeout(open, 15000);
  }

  /* A remembered choice is honoured on return. A browser locale is NOT applied
     automatically — English leads by decision, and silently switching the page
     out from under a visitor is a worse first impression than a click. */
  try {
    var saved = localStorage.getItem('co-register');
    if (saved && REG[saved]) setRegister(saved);
  } catch (e) {}

  /* ---------- sound ---------- */
  function fade(a, to, ms) { var f = a.volume, t0 = performance.now();
    (function s(n) { var k = Math.min(1, (n - t0) / ms); a.volume = f + (to - f) * k; if (k < 1) requestAnimationFrame(s); })(t0); }
  var sBtn = document.getElementById('soundBtn'), sOn = false;
  function setSound(on) {
    sOn = on; if (!sBtn) return;
    sBtn.classList.toggle('on', on); sBtn.setAttribute('aria-pressed', String(on));
    var l = sBtn.querySelector('.s-label');
    if (l) l.textContent = on ? '${soundLabel} ON' : '${soundLabel} OFF';
    try { localStorage.setItem('co-sound', on ? '1' : '0'); } catch (e) {}
  }
  if (sBtn && audio) {
    setSound(false);
    sBtn.addEventListener('click', function () {
      if (sOn) { fade(audio, 0, 350); setTimeout(function () { audio.pause(); }, 380); setSound(false); }
      else { audio.volume = 0; audio.play().then(function () { fade(audio, .5, 900); setSound(true); }).catch(function () {}); }
    });
  }

  /* ---------- the paperwork ----------
     Every readable surface is a panel you take out of the case: passport,
     baggage docket, manifest, customs form, her feed. */
  function openPanel(id) {
    var el = document.getElementById('panel-' + id);
    if (!el) return;
    document.querySelectorAll('.panel').forEach(function (n) { n.classList.remove('open'); n.setAttribute('aria-hidden', 'true'); });
    el.classList.add('open'); el.setAttribute('aria-hidden', 'false');
    var f = el.querySelector('button, a, input'); if (f) f.focus();
  }
  function closePanels() {
    document.querySelectorAll('.panel').forEach(function (n) { n.classList.remove('open'); n.setAttribute('aria-hidden', 'true'); });
  }
  document.querySelectorAll('[data-panel]').forEach(function (b) {
    b.addEventListener('click', function (e) { e.stopPropagation(); openPanel(b.getAttribute('data-panel')); });
  });
  document.querySelectorAll('.panel').forEach(function (n) {
    n.addEventListener('click', function (e) { if (e.target === n || e.target.dataset.close !== undefined) closePanels(); });
  });
  document.addEventListener('keydown', function (e) {
    if (e.key !== 'Escape') return;
    // the player sits above the panels, so Escape dismisses the top one only
    var pl = document.getElementById('player');
    if (pl && pl.classList.contains('open')) return;
    closePanels();
  });
  window.__coldopenPanel = openPanel;

  /* ---------- the player ----------
     A record opens IN the case. Sending someone to YouTube sends them off her
     site to a page that recommends somebody else's record next; the link out
     stays, under the player, as a choice rather than the only route. */
  var player = document.getElementById('player');
  var plIf = document.getElementById('pl-if');
  var plT = document.getElementById('pl-t');
  var plYt = document.getElementById('pl-yt');
  function openPlayer(id, title, sub) {
    if (!player || !id) return false;
    closePanels();
    plIf.src = 'https://www.youtube-nocookie.com/embed/' + id + '?autoplay=1&rel=0&modestbranding=1&playsinline=1';
    plT.innerHTML = title + (sub ? '<span>' + sub + '</span>' : '');
    plYt.href = 'https://www.youtube.com/watch?v=' + id;
    player.classList.add('open'); player.setAttribute('aria-hidden', 'false');
    var a = document.getElementById('bed');
    if (a && !a.paused) { a.pause(); setSound(false); }     // two things playing at once is nobody's idea
    return true;
  }
  function closePlayer() {
    if (!player) return;
    player.classList.remove('open'); player.setAttribute('aria-hidden', 'true');
    plIf.src = '';                                          // stop the audio, do not just hide it
  }
  document.querySelectorAll('[data-yt]').forEach(function (a) {
    a.addEventListener('click', function (e) {
      var id = a.getAttribute('data-yt');
      if (!id) return;                                      // no id parsed: let the link do its job
      e.preventDefault();
      openPlayer(id, a.getAttribute('data-title') || '', a.getAttribute('data-sub') || '');
    });
  });
  if (player) {
    player.addEventListener('click', function (e) {
      if (e.target === player || e.target.hasAttribute('data-close-player')) closePlayer();
    });
    document.addEventListener('keydown', function (e) { if (e.key === 'Escape') closePlayer(); });
  }

  /* ---------- the other bag ---------- */
  var bag = document.getElementById('bag');
  if (bag) bag.addEventListener('click', function () { openPanel('more'); });

  /* ---------- reveals + count-up ---------- */
  var io = 'IntersectionObserver' in window ? new IntersectionObserver(function (es) {
    es.forEach(function (e) {
      if (!e.isIntersecting) return;
      e.target.classList.add('in');
      e.target.querySelectorAll('[data-count]').forEach(countUp);
      io.unobserve(e.target);
    });
  }, { threshold: .12, rootMargin: '0px 0px -8% 0px' }) : null;
  document.querySelectorAll('.reveal').forEach(function (n) { if (io && !reduce) io.observe(n); else n.classList.add('in'); });

  function countUp(n) {
    var target = parseFloat(n.getAttribute('data-count'));
    if (!target || reduce || n.dataset.done) return;
    n.dataset.done = '1';
    var dur = 1400, t0 = performance.now();
    (function s(now) {
      var k = Math.min(1, (now - t0) / dur), e = 1 - Math.pow(1 - k, 3);
      n.textContent = Math.round(target * e).toLocaleString('en-US');
      if (k < 1) requestAnimationFrame(s); else n.textContent = target.toLocaleString('en-US');
    })(t0);
  }

  /* ---------- readout ---------- */
  var ro = document.getElementById('hudReadout');
  if (ro && !reduce) {
    var b0 = ro.textContent;
    window.addEventListener('scroll', function () {
      var p = Math.min(100, Math.round(scrollY / Math.max(1, document.body.scrollHeight - innerHeight) * 100));
      ro.textContent = b0 + ' · ' + String(p).padStart(3, '0') + '%';
    }, { passive: true });
  }

  /* ---------- the rail ---------- */
  var form = document.getElementById('railForm'), msg = document.getElementById('formMsg');
  if (form) form.addEventListener('submit', function (e) {
    e.preventDefault();
    if (form.querySelector('[name="_gotcha"]').value) return;
    var b = form.querySelector('button[type="submit"]'), o = b.textContent;
    b.disabled = true; b.textContent = 'SENDING…'; msg.className = 'form-msg mono'; msg.textContent = '';
    fetch(form.action, { method: 'POST', body: new FormData(form), headers: { Accept: 'application/json' } })
      .then(function (r) { if (!r.ok) throw new Error('HTTP ' + r.status);
        form.reset(); msg.className = 'form-msg mono ok'; msg.textContent = 'RECEIVED. YOU WILL HEAR BACK.'; })
      .catch(function (err) { msg.className = 'form-msg mono err'; msg.textContent = 'DID NOT SEND (' + err.message + '). EMAIL INSTEAD.'; })
      .finally(function () { b.disabled = false; b.textContent = o; });
  });
})();
`;
}
