/**
 * TEST 1 — shortiieraw.com, generated by the engine.
 *
 * World chosen: RÁDIO KINAXIXI (broadcast). The gate produced three; this is
 * the one that makes the load-bearing finding navigable — her comment audience
 * is Portuguese and Angola-flagged, her streaming audience is 43% Canada, and
 * they are two different audiences. A dial makes that literal.
 *
 * Kinaxixi is a real square in Luanda and the title of her own 2024 freestyle.
 * The name is hers, not ours.
 *
 * Nothing below is invented. Every figure resolves through ledger.json, which
 * refuses any fact without a source URL and a read date.
 */
import fs from 'node:fs';
import path from 'node:path';
import { Ledger } from '../../engine/src/ledger.ts';
import { derive } from '../../engine/src/derive.ts';
import { build } from '../../engine/src/emit/index.ts';
import type { SiteContent, Unit } from '../../engine/src/emit/html.ts';
import type { PremiseDraft } from '../../engine/src/premise.ts';

const HERE = path.dirname(new URL(import.meta.url).pathname);
const OUT = path.join(HERE, 'site');
const ledger = Ledger.fromJSON(JSON.parse(fs.readFileSync(path.join(HERE, 'ledger.json'), 'utf8')));

/** the premise the divergence gate passed, chosen by a human */
const premise: PremiseDraft = {
  name: 'Rádio Kinaxixi',
  logline: 'A station already playing in Portuguese when you arrive. Turn the dial to find the frequency you can understand.',
  topology: 'broadcast',
  ground: '#C81E1E',
  // The gate's cyan could not clear 3:1 on this red at any usable saturation —
  // on a vermilion ground the GROUND is the loud hue. This yellow is the other
  // half of the Angolan flag and the diagonal band on her own Sip Cuca cover:
  // https://i.scdn.co/image/ab67616d00001e02148e9058765dbf03a95502dc
  accent: '#FFDD33',
  thresholdGesture: 'turn',
  thresholdLabel: 'SINTONIZAR — FIND THE SIGNAL',
  lexicon: {
    enter: 'SINTONIZAR', catalogue: 'THE PLAYLIST', story: 'STATION IDENT',
    proof: 'CALLERS ON THE LINE', contact: 'THE BOOKING LINE', latest: 'NOW PLAYING',
    unit: 'TRANSMISSION', index: 'THE DIAL',
  },
  rationale: 'From [wrong]: the comment audience and the streaming audience are two different audiences.',
  fromAnswers: ['wrong', 'sound_on', 'room'],
};

const world = {
  ...derive({
    premise,
    artist: 'SHORTIIE RAW',
    domain: 'shortiieraw.com',
    ground: {
      kind: 'image' as const,
      src: 'assets/yt-Xedv19NEX-E.jpg',
      treatment: ['grain', 'vignette', 'scanlines'] as const,
      // she stands centre-frame in this shot; centred copy would sit on her
      copyAnchor: 'top' as const,
      focus: '50% 62%',
    },
    sound: { src: 'assets/bed.mp3', label: 'ON AIR', startsMuted: true },
  }),
  // She raps in three languages and her two audiences read in two of them.
  // Allowed only because 'artist.languages' is a sourced fact.
  registers: [
    {
      code: 'en', label: 'EN', evidenceId: 'artist.languages',
      lexicon: {}, logline: premise.logline, story: [],
    },
    {
      code: 'pt', label: 'PT', evidenceId: 'artist.languages',
      logline: 'Uma estação já a tocar quando chegas. Roda o botão até encontrares a frequência que entendes.',
      lexicon: {
        catalogue: 'A LISTA', story: 'IDENTIFICAÇÃO DA ESTAÇÃO', proof: 'OUVINTES NA LINHA',
        contact: 'A LINHA DE CONTACTO', latest: 'A TOCAR AGORA', index: 'O BOTÃO', enter: 'SINTONIZAR',
      },
      story: [
        'Nasceu em Lisboa. Chegou a Toronto aos seis anos sem falar inglês. Hoje faz rap em três línguas.',
        'Os comentários dos seus vídeos estão em português e trazem a bandeira de Angola. As estatísticas de streaming dizem 43% Canadá. São dois públicos diferentes a ler a mesma artista.',
        'Esta estação toca para os dois.',
      ],
    },
  ],
};

/** Her catalogue, every figure read from the platform on 2026-08-21. */
const units: Unit[] = [
  { title: 'Drip', sub: 'ft. Molly Brazy · 202,424 views', href: 'https://www.youtube.com/watch?v=EmrpNsyVtDQ', image: 'assets/yt-EmrpNsyVtDQ.jpg', sourceId: 'drip.youtube' },
  { title: 'Sip Cuca', sub: '2025 · 7,463 views', href: 'https://www.youtube.com/watch?v=NbJnT5j365M', image: 'assets/yt-NbJnT5j365M.jpg' },
  { title: 'Way We Move', sub: 'ft. Ingomblock · 11,985 views', href: 'https://www.youtube.com/watch?v=Xedv19NEX-E', image: 'assets/yt-Xedv19NEX-E.jpg' },
  { title: 'Angola Kinaxixi Freestyle', sub: 'reprod. AK Marv · 8,676 views', href: 'https://www.youtube.com/watch?v=X8zj9clGQO4', image: 'assets/yt-X8zj9clGQO4.jpg' },
  { title: 'Peace', sub: '2023 · 11,212 views', href: 'https://www.youtube.com/watch?v=z2BL7wgPsaI', image: 'assets/yt-z2BL7wgPsaI.jpg' },
  { title: 'Fire', sub: 'In-studio performance · 8,024 views', href: 'https://www.youtube.com/watch?v=82_xVuYR45c', image: 'assets/yt-82_xVuYR45c.jpg' },
  { title: "Don't Act New", sub: '2021 · 14,609 views', href: 'https://www.youtube.com/watch?v=HueUBufXMbs', image: 'assets/yt-HueUBufXMbs.jpg' },
  { title: 'Cartier Tints', sub: '2024 · 6,367 views', href: 'https://www.youtube.com/watch?v=9hRUzEGfW7o', image: 'assets/yt-9hRUzEGfW7o.jpg' },
  { title: 'Sexy No Jutsu', sub: 'prod. Cash Money AP · 5,736 views', href: 'https://www.youtube.com/watch?v=WLnquJAMnt0', image: 'assets/yt-WLnquJAMnt0.jpg' },
  { title: 'Strawberry Go-Kart', sub: '2018 · 31,890 views', href: 'https://www.youtube.com/watch?v=iiYmh9-D_14', image: 'assets/yt-iiYmh9-D_14.jpg' },
];

const content: SiteContent = {
  title: 'SHORTIIE RAW — Rádio Kinaxixi',
  description: 'Toronto by way of Lisbon and Luanda. Rap in three languages. A station already playing when you arrive.',
  canonical: 'https://shortiieraw.com/',
  ogImage: 'https://shortiieraw.com/assets/yt-Xedv19NEX-E.jpg',
  figures: ['drip.spotify', 'drip.youtube', 'catalogue.streams', 'reach.followers', 'x.followers', 'yt.subs', 'instagram.followers'],
  units,
  climax: {
    stamp: 'HEAVIEST ROTATION',
    title: 'DRIP',
    sub: 'ft. Molly Brazy · 455,493 Spotify streams · 202,424 views · 211,091 SoundCloud plays',
    href: 'https://www.youtube.com/watch?v=EmrpNsyVtDQ',
  },
  story: [
    'Born in Lisbon. Landed in Toronto at six speaking no English — "You\'re black, how do you not speak English?" is how she remembers being asked. She raps in three languages now.',
    'The comments under her videos are in Portuguese and flagged Angola. The streaming map says 43% Canada, 26% United States, and no Angola at all. Those are two different audiences reading the same artist.',
    'This station plays to both of them. Turn the dial.',
  ],
  rail: {
    endpoint: 'https://formsubmit.co/ajax/bookingshortiieraw@gmail.com',
    fields: [
      { name: 'name', label: 'WHO IS CALLING', type: 'text', required: true },
      { name: 'email', label: 'CALL YOU BACK ON', type: 'email', required: true },
      { name: 'reason', label: 'WHAT FOR', type: 'select', required: true, options: ['A feature', 'A show', 'Press / interview', 'Something else'] },
      { name: 'message', label: 'THE MESSAGE', type: 'textarea', required: true },
    ],
    submitLabel: 'PUT IT THROUGH',
    fallbackEmail: 'bookingshortiieraw@gmail.com',
  },
  links: ledger.all().filter(f => f.kind === 'link' && f.id.startsWith('link.'))
    .map(f => ({ label: f.label, href: String(f.value) })),
  jsonLd: {
    '@context': 'https://schema.org', '@type': 'MusicGroup', '@id': 'https://shortiieraw.com/#artist',
    name: 'Shortiie Raw', url: 'https://shortiieraw.com/',
    genre: ['Hip-Hop', 'Rap', 'Trap'],
    birthPlace: { '@type': 'Place', name: 'Lisbon, Portugal' },
    foundingLocation: { '@type': 'Place', name: 'Toronto, Ontario, Canada' },
    knowsLanguage: ['en', 'pt', 'es'],
    description: 'Toronto rapper, born in Lisbon of Angolan family. Raps in English, Portuguese and Spanish.',
    sameAs: ledger.all().filter(f => f.id.startsWith('link.')).map(f => String(f.value)),
  },
};

const out = build(world as any, content, ledger);
console.log('── AUDIT ──');
console.log(`  moves ${out.audit.moveCount}/7   ink ${out.audit.contrast.inkOnGround.toFixed(2)}:1   accent ${out.audit.contrast.accentOnGround.toFixed(2)}:1`);
console.log(out.audit.ok ? '  ✓ clean' : out.audit.problems.map(p => '  ✕ ' + p).join('\n'));

fs.mkdirSync(OUT, { recursive: true });
for (const [rel, body] of Object.entries(out.files)) {
  const p = path.join(OUT, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, body);
}
fs.cpSync(path.join(HERE, 'assets'), path.join(OUT, 'assets'), { recursive: true });
console.log(`\n  ${Object.keys(out.files).length} files → ${OUT}`);
